### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by rkaminsk** [krr-up/bibliography#1]
I think we should encourage people to use the bibliography as a submodule in their projects. In view of this, I think we should rewrite the installation section. What do you think?

**Comment by pluehne** [comment]
@rkaminsk: I agree that having a section on how to use this submodule makes sense. Also, turning this repository public is perfectly fine. I just did it in fact :slightly_smiling_face:.

**Comment by tortinator** [comment]
Making it public is a good move.
How shall we deal with pull requests?

**Comment by pluehne** [comment]
@tortinator: Given that using `bibtool` turned out to be more complicated than anticipated (I get segfaults with the configuration I’d like to have), we’ll need to manually review pull requests until we find an automated way to do so.

**Comment by tortinator** [comment]
@pluehne fine with me

**Comment by rkaminsk** [comment]
@pluehne: Have you tried biber?

**Comment by tortinator** [comment]
@rkaminsk The biber command you sent yields a bib file quite different from what we are used to ...

**Comment by rkaminsk** [comment]
> biber --tool --output-safechars krr.bib
> yields a bib file quite different from what we are used to ...

True, but there are options to make it more similar to what was there before. A good thing is that biber should be fully bibtex compatible. -R

**Comment by rkaminsk** [comment]
Biber does not provide enough options for customization. Or at least I do not find them. That's why there is a relatively lightweight script `format.py` now. See #63.
