### ISSUE TITLE
ASP-Core-2 publications appears twice

### ISSUE THREAD

**Issue by nrueh** [krr-up/bibliography#172]
The ASP-Core-2 TPLP publication appears twice. Once the year seems to be wrong?

https://github.com/krr-up/bibliography/blob/e67a140d528ccaa38a353950ab5593ea14adc4dd/krr.bib#L5721-L5740

**Comment by tortinator** [comment]
Danke, @nrueh !

**Comment by tortinator** [comment]
Merci
