### ISSUE TITLE
Explicit Negation in Linear-Dynamic Equilibrium Logic, ECAI'20

### ISSUE THREAD

**Issue by tortinator** [krr-up/bibliography#65]
Just retrieved the bib entry (and issued a PR to @rkaminsk) 

+@inproceedings{DBLP:conf/ecai/AguadoCFPV20,
+    author = "Aguado, Felicidad and Cabalar, Pedro and Fandinno, Jorge and P{\'{e}}rez, Gilberto and Vidal, Concepci{\'{o}}n",
+    title = "Explicit Negation in Linear-Dynamic Equilibrium Logic",
+    booktitle = "{ECAI}",
+    series = "Frontiers in Artificial Intelligence and Applications",
+    volume = "325",
+    pages = "569--576",
+    publisher = "{IOS} Press",
+    year = "2020"
+}

Would you mind adding the PDF, @jorgefandinno ..?

PS Checkout the the repo on the local disk on your machine at Potsdam ;)

**Comment by jorgefandinno** [comment]
Done. Created pull-request

**Comment by tortinator** [comment]
Hola @jorgefandinno , I cannot find a pull request...? Just one for the website. @tortinator

**Comment by tortinator** [comment]
Stupid me! Of course, I put the issue in the wrong repo, sigh! Chao @tortinator
